# Generated by Django 5.2.10 on 2026-03-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
